create table if not exists tb01_usuario (
    id bigint generated by default as identity,
    email varchar(255) not null,
    nome varchar(255) not null,
    senha varchar(255) not null,
    primary key (id)
)